package firewall

import (
	"context"
	"io"
	"log/slog"
	"net/netip"
	"os"
	"path/filepath"
	"testing"
	"time"

	"graphrelay/internal/store"
)

func TestExport(t *testing.T) {
	dir := t.TempDir()
	st, err := store.Open(filepath.Join(dir, "relay.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()

	for _, h := range []store.Host{
		{Name: "ip", Match: "192.0.2.10", Sender: "a@x.test", Enabled: true},
		{Name: "net", Match: "198.51.100.0/24", Sender: "b@x.test", Enabled: true},
		{Name: "v6", Match: "2001:db8::/64", Sender: "c@x.test", Enabled: true},
		{Name: "dns", Match: "printer.x.test", Sender: "d@x.test", Enabled: true},
		{Name: "off", Match: "192.0.2.99", Sender: "e@x.test", Enabled: false},
	} {
		if err := st.SaveHost(&h); err != nil {
			t.Fatal(err)
		}
	}
	resolve := func(_ context.Context, name string) []netip.Addr {
		if name == "printer.x.test" {
			// One duplicate of an existing rule, one new address.
			return []netip.Addr{netip.MustParseAddr("192.0.2.10"), netip.MustParseAddr("192.168.5.7")}
		}
		return nil
	}
	path := filepath.Join(dir, "allowlist")
	e := &Exporter{Store: st, Resolve: resolve, Path: path, Log: slog.New(slog.NewTextHandler(io.Discard, nil))}
	if err := e.Export(context.Background()); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by graphrelay from the enabled host rules. Do not edit.\n" +
		"192.0.2.10/32\n192.168.5.7/32\n198.51.100.0/24\n2001:db8::/64\n"
	if string(got) != want {
		t.Fatalf("allowlist:\n%s\nwant:\n%s", got, want)
	}

	// Unchanged content must not rewrite the file (the root-side path unit would reload for nothing).
	before, _ := os.Stat(path)
	time.Sleep(20 * time.Millisecond)
	if err := e.Export(context.Background()); err != nil {
		t.Fatal(err)
	}
	after, _ := os.Stat(path)
	if !after.ModTime().Equal(before.ModTime()) {
		t.Fatal("file was rewritten although nothing changed")
	}
}

func TestNotifyDoesNotBlock(t *testing.T) {
	e := &Exporter{}
	for i := 0; i < 5; i++ {
		e.Notify()
	}
}
