// Package firewall exports the enabled host rules as a plain list of IP prefixes, so a
// privileged helper outside the relay can load them into the host firewall. The relay itself
// never needs CAP_NET_ADMIN.
package firewall

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"time"

	"graphrelay/internal/store"
)

// Exporter writes the allowlist file. One prefix per line, IPv4 and IPv6 mixed, sorted.
type Exporter struct {
	Store   *store.Store
	Resolve func(ctx context.Context, name string) []netip.Addr
	Path    string
	Log     *slog.Logger

	notify chan struct{}
}

// refreshInterval matches the matcher's DNS cache TTL, so DNS host rules follow address changes.
const refreshInterval = 2 * time.Minute

func (e *Exporter) init() {
	if e.notify == nil {
		e.notify = make(chan struct{}, 1)
	}
}

// Notify asks Run to rewrite the file soon. It never blocks.
func (e *Exporter) Notify() {
	e.init()
	select {
	case e.notify <- struct{}{}:
	default:
	}
}

// Run writes the file at start, after every Notify and every refreshInterval until ctx ends.
func (e *Exporter) Run(ctx context.Context) {
	e.init()
	t := time.NewTicker(refreshInterval)
	defer t.Stop()
	for {
		if err := e.Export(ctx); err != nil {
			e.Log.Error("firewall allowlist export failed", "err", err)
		}
		select {
		case <-ctx.Done():
			return
		case <-e.notify:
		case <-t.C:
		}
	}
}

// Prefixes returns the deduplicated, sorted prefixes of all enabled host rules.
func (e *Exporter) Prefixes(ctx context.Context) ([]netip.Prefix, error) {
	hosts, err := e.Store.ListHosts()
	if err != nil {
		return nil, err
	}
	seen := map[netip.Prefix]bool{}
	add := func(p netip.Prefix) { seen[p.Masked()] = true }
	for _, h := range hosts {
		if !h.Enabled {
			continue
		}
		if a, err := netip.ParseAddr(h.Match); err == nil {
			a = a.Unmap()
			add(netip.PrefixFrom(a, a.BitLen()))
			continue
		}
		if p, err := netip.ParsePrefix(h.Match); err == nil {
			if p.Addr().Is4In6() {
				p = netip.PrefixFrom(p.Addr().Unmap(), max(p.Bits()-96, 0))
			}
			add(p)
			continue
		}
		for _, a := range e.Resolve(ctx, h.Match) {
			a = a.Unmap()
			add(netip.PrefixFrom(a, a.BitLen()))
		}
	}
	out := make([]netip.Prefix, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	slices.SortFunc(out, func(a, b netip.Prefix) int {
		if c := a.Addr().Compare(b.Addr()); c != 0 {
			return c
		}
		return a.Bits() - b.Bits()
	})
	return out, nil
}

// Export rewrites the file atomically, only when its content changes.
func (e *Exporter) Export(ctx context.Context) error {
	prefixes, err := e.Prefixes(ctx)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by graphrelay from the enabled host rules. Do not edit.\n")
	for _, p := range prefixes {
		fmt.Fprintln(&buf, p)
	}
	if old, err := os.ReadFile(e.Path); err == nil && bytes.Equal(old, buf.Bytes()) {
		return nil
	}
	tmp, err := os.CreateTemp(filepath.Dir(e.Path), ".allowlist-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(buf.Bytes()); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp.Name(), e.Path); err != nil {
		return err
	}
	e.Log.Info("firewall allowlist updated", "path", e.Path, "entries", len(prefixes))
	return nil
}
